jobs:
  - name: pipelines-demo-manifest
    type: manifest
    steps:
     - IN: pipelines-demo-image
     - IN: pipelines-demo-image2
     - IN: pipelines-demo-image3
     - IN: pipelines-demo-image4
     - IN: pipelines-demo-image5
     - TASK: managed
    on_success:
     - NOTIFY: irc

  - name: pipelines-demo-manifest-2
    type: manifest
    steps:
     - IN: deploy-pipelines-demo
     - TASK: managed
        
     - NOTIFY: irc

  - name: pipelines-demo-manifest-3
    type: manifest
    steps:
     - IN: deploy-pipelines-demo
     - TASK: managed

  - name: pipelines-demo-manifest-42
    type: manifest
    steps:
     - IN: deploy-pipelines-demo
     - TASK: managed

  - name: pipelines-demo-manifest-25
    type: manifest
    steps:
     - IN: deploy-pipelines-demo
     - TASK: managed

  - name: pipelines-demo-manifest-21
    type: manifest
    steps:
     - IN: deploy-pipelines-demo
     - TASK: managed
 

  - name: pipelines-demo-manifest-3312
    type: manifest
    steps:
     - IN: deploy-pipelines-demo
     - TASK: managed

  - name: pipelines-demo-manifest-4232
    type: manifest
    steps:
     - IN: deploy-pipelines-demo
     - TASK: managed

  - name: pipelines-demo-manifest-25222
    type: manifest
    steps:
     - IN: deploy-pipelines-demo
     - TASK: managed

  - name: pipelines-demo-manifest-21333
    type: manifest
    steps:
     - IN: deploy-pipelines-demo
     - TASK: managed
  - name: deploy-pipelines-demo
    type: deploy
    flags:
      - job-flag
    steps:
      - IN: pipelines-demo-manifest
      - IN: docker-options
      - IN: ecs-cluster
      - IN: replicas
      - TASK: managed
        deployMethod: upgrade

  - name: runSh
    type: runSh
    steps:
      - IN: pipelines-demo-manifest
      - TASK:
        - script: echo 'This block executes when the TASK starts'
        - script: echo "versionName=satble" >> $JOB_STATE/runSh.env;


  - name: runSh3
    type: runSh
    steps:
      - IN: deploy-pipelines-demo
      - TASK:
        - script: echo 'This block executes when the TASK starts'
        - script: echo "versionName=satble" >> $JOB_STATE/runSh3.env;


  - name: pipelines-demo-manifest-2asdd
    type: manifest
    steps:
     - IN: runSh3
     - TASK: managed
        
     - NOTIFY: irc

  - name: pipelines-demo-manifest-3dddd
    type: manifest
    steps:
     - IN: runSh3
     - TASK: managed

  - name: pipelines-demo-manifest-42sddd
    type: manifest
    steps:
     - IN: runSh3
     - TASK: managed

  - name: pipelines-demo-manifest-25sddd
    type: manifest
    steps:
     - IN: runSh3
     - TASK: managed

  - name: pipelines-demo-manifest-21asaa
    type: manifest
    steps:
     - IN: runSh3
     - TASK: managed
 

  - name: pipelines-demo-manifest-3312as
    type: manifest
    steps:
     - IN: runSh3
     - TASK: managed

  - name: pipelines-demo-manifest-4232as
    type: manifest
    steps:
     - IN: runSh3
     - TASK: managed

  - name: pipelines-demo-manifest-25222d
    type: manifest
    steps:
     - IN: runSh3
     - TASK: managed

  - name: pipelines-demo-manifest-21333as
    type: manifest
    steps:
     - IN: runSh3
     - TASK: managed
     

  - name: pipelines-demo-manifest-2as
    type: manifest
    steps:
     - IN: runSh3
     - TASK: managed
        
     - NOTIFY: irc

  - name: pipelines-demo-manifest-3dd
    type: manifest
    steps:
     - IN: runSh3
     - TASK: managed

  - name: pipelines-demo-manifest-42sd
    type: manifest
    steps:
     - IN: runSh3
     - TASK: managed

  - name: pipelines-demo-manifest-25sd
    type: manifest
    steps:
     - IN: runSh3
     - TASK: managed

  - name: pipelines-demo-manifest-21as
    type: manifest
    steps:
     - IN: runSh3
     - TASK: managed
 

  - name: pipelines-demo-manifest-33s12as
    type: manifest
    steps:
     - IN: runSh
     - TASK: managed

  - name: pipelines-demo-manifest-4232ssas
    type: manifest
    steps:
     - IN: runSh
     - TASK: managed

  - name: pipelines-demo-manifest-25ddas222d
    type: manifest
    steps:
     - IN: runSh
     - TASK: managed

  - name: pipelines-demo-manifest-21s33as
    type: manifest
    steps:
     - IN: runSh
     - TASK: managed


# new


  - name: newManifesta
    type: manifest
    steps:
     - IN: pipelines-demo-manifest
     - TASK: managed

  - name: newManifestb
    type: manifest
    steps:
     - IN: pipelines-demo-manifest
     - TASK: managed

  - name: newManifestc
    type: manifest
    steps:
     - IN: pipelines-demo-manifest
     - TASK: managed

  - name: newManifests
    type: manifest
    steps:
     - IN: pipelines-demo-manifest
     - TASK: managed

  - name: newManifestddd
    type: manifest
    steps:
     - IN: pipelines-demo-manifest
     - TASK: managed

  - name: newManifestafa
    type: manifest
    steps:
     - IN: pipelines-demo-manifest
     - TASK: managed

  - name: newManifestsssd
    type: manifest
    steps:
     - IN: pipelines-demo-manifest
     - TASK: managed

  - name: newManifestadaas
    type: manifest
    steps:
     - IN: pipelines-demo-manifest
     - TASK: managed

# new2


  - name: newManifest2
    type: manifest
    steps:
     - IN: pipelines-demo-manifest-21as
     - IN: pipelines-demo-image
     - IN: pipelines-demo-image2
     - IN: pipelines-demo-image3
     - IN: pipelines-demo-image4
     - IN: pipelines-demo-image5
     - TASK: managed

  - name: newManifest23
    type: manifest
    steps:
     - IN: pipelines-demo-manifest-21as
     - IN: pipelines-demo-image
     - IN: pipelines-demo-image2
     - IN: pipelines-demo-image3
     - IN: pipelines-demo-image4
     - IN: pipelines-demo-image5
     - TASK: managed

  - name: newManifest3
    type: manifest
    steps:
     - IN: pipelines-demo-manifest-21as
     - IN: pipelines-demo-image
     - IN: pipelines-demo-image2
     - IN: pipelines-demo-image3
     - IN: pipelines-demo-image4
     - IN: pipelines-demo-image5
     - TASK: managed

  - name: newManifest232
    type: manifest
    steps:
     - IN: pipelines-demo-manifest-21as
     - IN: pipelines-demo-image
     - IN: pipelines-demo-image2
     - IN: pipelines-demo-image3
     - IN: pipelines-demo-image4
     - IN: pipelines-demo-image5
     - TASK: managed

  - name: newManifest2s
    type: manifest
    steps:
     - IN: pipelines-demo-manifest-21as
     - IN: pipelines-demo-image
     - IN: pipelines-demo-image2
     - IN: pipelines-demo-image3
     - IN: pipelines-demo-image4
     - IN: pipelines-demo-image5
     - TASK: managed

  - name: newManifestwds
    type: manifest
    steps:
     - IN: pipelines-demo-manifest-21as
     - IN: pipelines-demo-image
     - IN: pipelines-demo-image2
     - IN: pipelines-demo-image3
     - IN: pipelines-demo-image4
     - IN: pipelines-demo-image5
     - TASK: managed

  - name: newManifestasdw
    type: manifest
    steps:
     - IN: pipelines-demo-manifest-21as
     - IN: pipelines-demo-image
     - IN: pipelines-demo-image2
     - IN: pipelines-demo-image3
     - IN: pipelines-demo-image4
     - IN: pipelines-demo-image5
     - TASK: managed

  - name: newManifestaa
    type: manifest
    steps:
     - IN: pipelines-demo-manifest-21as
     - IN: pipelines-demo-image
     - IN: pipelines-demo-image2
     - IN: pipelines-demo-image3
     - IN: pipelines-demo-image4
     - IN: pipelines-demo-image5
     - TASK: managed

# new3


  - name: newManifest2xzx
    type: manifest
    steps:
     - IN: newManifestc
     - IN: pipelines-demo-image
     - IN: pipelines-demo-image2
     - IN: pipelines-demo-image3
     - IN: pipelines-demo-image4
     - IN: pipelines-demo-image5
     - TASK: managed

  - name: newManifest23cczx
    type: manifest
    steps:
     - IN: newManifestc
     - IN: pipelines-demo-image
     - IN: pipelines-demo-image2
     - IN: pipelines-demo-image3
     - IN: pipelines-demo-image4
     - IN: pipelines-demo-image5
     - TASK: managed

  - name: newManifest3bb
    type: manifest
    steps:
     - IN: newManifestc
     - IN: pipelines-demo-image
     - IN: pipelines-demo-image2
     - IN: pipelines-demo-image3
     - IN: pipelines-demo-image4
     - IN: pipelines-demo-image5
     - TASK: managed

  - name: newManifest232zxx
    type: manifest
    steps:
     - IN: newManifestc
     - IN: pipelines-demo-image
     - IN: pipelines-demo-image2
     - IN: pipelines-demo-image3
     - IN: pipelines-demo-image4
     - IN: pipelines-demo-image5
     - TASK: managed

  - name: newManifest2sw
    type: manifest
    steps:
     - IN: newManifestc
     - IN: pipelines-demo-image
     - IN: pipelines-demo-image2
     - IN: pipelines-demo-image3
     - IN: pipelines-demo-image4
     - IN: pipelines-demo-image5
     - TASK: managed

  - name: newManifestwdsasd
    type: manifest
    steps:
     - IN: newManifestc
     - IN: pipelines-demo-image
     - IN: pipelines-demo-image2
     - IN: pipelines-demo-image3
     - IN: pipelines-demo-image4
     - IN: pipelines-demo-image5
     - TASK: managed

  - name: newManifestasdwwe
    type: manifest
    steps:
     - IN: newManifestc
     - TASK: managed

  - name: newManifestaaa22
    type: manifest
    steps:
     - IN: newManifestc
     - IN: pipelines-demo-image
     - IN: pipelines-demo-image2
     - IN: pipelines-demo-image3
     - IN: pipelines-demo-image4
     - IN: pipelines-demo-image5
     - TASK: managed
